name: Build frontend docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker login to registry
      run: echo "${{ secrets.REGISTRY_PASS }}" | docker login rg.fr-par.scw.cloud/babyteacher-regitstry -u nologin --password-stdin
    - name: Build the Docker image for the frontend
      run: docker build . --tag rg.fr-par.scw.cloud/babyteacher-registry/frontend:latest
    - name: Push the image to private registry
      run: docker push rg.fr-par.scw.cloud/babyteacher-registry/frontend
