name: 'terraform-trigger'

on:
  push:
    branches:
      - main

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger terraform workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with: 
          owner: SurfingOwl
          repo: iac_terraform
          github_token: ${{ secrets.ACTIONS_KEY }}
          workflow_file_name: terraform_deploy.yml
          ref: main
          wait_interval: 30
          propagate_failure: true
          wait_workflow: true
